- Condition:
    KeyPrefixEquals: "blog/2013/11/physical-computing-article-on-make-magazine"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: medium.com
    ReplaceKeyWith: "@bashaus/web-based-physical-computing-1213fafb448c"

- Condition:
    KeyPrefixEquals: "blog/2013/07/web-based-physical-computing"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: medium.com
    ReplaceKeyWith: "@bashaus/web-based-physical-computing-1213fafb448c"

- Condition:
    KeyPrefixEquals: "blog/2013/01/accessing-apache-from-across-a-network"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: medium.com
    ReplaceKeyWith: "@bashaus/accessing-a-web-server-from-across-your-network-b6f8e6fe90b6"

- Condition:
    KeyPrefixEquals: "blog/2014/09/launched-facebook-page-for-game-boy-homebrew-developers"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.facebook.com
    ReplaceKeyWith: "gbdk.developers/"

- Condition:
    KeyPrefixEquals: "blog/2014/12/gbtiles-ruby-gem-released"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: rubygems.org
    ReplaceKeyWith: "gems/gbtiles"

- Condition:
    KeyPrefixEquals: "blog/2015/06/looking-for-you-cannes-lions"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio/battersea-looking-for-you"

- Condition:
    KeyPrefixEquals: "blog/2015/12/looking-for-you-dma-awards"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio/battersea-looking-for-you"

- Condition:
    KeyPrefixEquals: "blog/2015/12/campaign-battersea-top-10-in-2015"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio/battersea-looking-for-you"

- Condition:
    KeyPrefixEquals: "blog"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: medium.com
    ReplaceKeyWith: "@bashaus"

- Condition:
    KeyPrefixEquals: "contact"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "about"

- Condition:
    KeyPrefixEquals: "portfolio.html"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio"

- Condition:
    KeyPrefixEquals: "portfolio-ludic-lift.html"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio/ludic-lift"

- Condition:
    KeyPrefixEquals: "talks.html"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio"

- Condition:
    KeyPrefixEquals: "project/commodore/interaction-game-play.html"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: http
    HostName: commodore-game.com
    ReplaceKeyWith: "interaction-game-play.html"

- Condition:
    KeyPrefixEquals: "project/commodore/interaction-starting-a-game.html"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: http
    HostName: commodore-game.com
    ReplaceKeyWith: "interaction-starting-a-game.html"

- Condition:
    KeyPrefixEquals: "publicity/2010/10/studio-farrago-at-pecha-kucha-brisbane"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: medium.com
    ReplaceKeyWith: "@bashaus/studio-farrago-at-pecha-kucha-brisbane-ca86cb5f39fa"

- Condition:
    KeyPrefixEquals: "publicity/2010/11/meet-eater-articles"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio/meet-eater"

- Condition:
    KeyPrefixEquals: "publicity/2013/12/model-engineer-show-2013"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: medium.com
    ReplaceKeyWith: "@bashaus/model-engineering-show-2013-9c19a703442f"

- Condition:
    KeyPrefixEquals: "publicity/2014/01/message-queues-article-published-on-sitepoint"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.sitepoint.com
    ReplaceKeyWith: "message-queues-comparing-beanstalkd-ironmq-amazon-sqs/"

- Condition:
    KeyPrefixEquals: "publicity/2015/05/feature-detection-article-published-on-sitepoint"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.sitepoint.com
    ReplaceKeyWith: "migrating-flexbox-cutting-mustard/"

- Condition:
    KeyPrefixEquals: "publicity"
  Redirect:
    HttpRedirectCode: "301"
    Protocol: https
    HostName: www.bashkim.com
    ReplaceKeyWith: "portfolio"
