extensions:
  languageService:
    cacheSchemaFileForLookup: true
    useSchemaFileDefinitions: true

projects:
  prismic-dal:
    schema: "./packages/prismic-dal/dist/prismic.schema.gql"
    documents:
      - "./packages/prismic-dal/src/**/*.gql"

  socials-github:
    schema: "./packages/socials/graphql/github/schema.gql"
    documents:
      - "./packages/socials/graphql/github/queries/**/*.gql"
      - "./packages/socials/graphql/github/mutations/**/*.gql"
