extensions:
  languageService:
    cacheSchemaFileForLookup: true
    useSchemaFileDefinitions: true

projects:
  prismic-dal:
    schema: "./packages/prismic-dal/generated/prismic/schema.gql"
    documents:
      - "./packages/prismic-dal/src/**/*.gql"

  socials-github:
    schema: "./packages/socials/generated/github/schema.gql"
    documents:
      - "./packages/socials/graphql/github/**/*.gql"
