const config = {
  js2svg: {
    indent: 2,
    pretty: true,
  },
  plugins: [
    { name: "cleanupAttrs" },
    { name: "cleanupEnableBackground" },
    { name: "cleanupIds" },
    { name: "cleanupListOfValues" },
    { name: "cleanupNumericValues", params: { floatPrecision: 2 } },
    { name: "collapseGroups" },
    { name: "convertColors" },
    { name: "convertEllipseToCircle" },
    { name: "convertPathData" },
    { name: "convertShapeToPath" },
    { name: "convertStyleToAttrs" },
    { name: "convertTransform" },
    { name: "inlineStyles" },
    { name: "mergePaths" },
    { name: "mergeStyles" },
    { name: "minifyStyles" },
    { name: "moveElemsAttrsToGroup" },
    { name: "moveGroupAttrsToElems" },
    // { name: "removeAttrs" },
    { name: "removeComments" },
    { name: "removeDesc" },
    // { name: "removeDimensions" },
    { name: "removeDoctype" },
    { name: "removeEditorsNSData" },
    { name: "removeEmptyAttrs" },
    { name: "removeEmptyContainers" },
    { name: "removeEmptyText" },
    { name: "removeHiddenElems" },
    { name: "removeMetadata" },
    { name: "removeNonInheritableGroupAttrs" },
    { name: "removeTitle" },
    { name: "removeUnknownsAndDefaults" },
    { name: "removeUnusedNS" },
    { name: "removeUselessDefs" },
    { name: "removeUselessStrokeAndFill" },
    // { name: "removeViewBox" },
    // { name: "removeXMLNS" },
    { name: "removeXMLProcInst" },
    { name: "sortAttrs" },
    { name: "sortDefsChildren" },
  ],
};

export default config;
