---
plugins:
  cleanupAttrs: true
  mergeStyles: true
  inlineStyles: true
  removeDoctype: true
  removeXMLProcInst: true
  removeComments: true
  removeMetadata: true
  removeTitle: true
  removeDesc: true
  removeUselessDefs: true
  removeEditorsNSData: true
  removeEmptyAttrs: true
  removeHiddenElems: true
  removeEmptyText: true
  removeEmptyContainers: true
  removeViewBox: false
  removeDimensions: true
  cleanupEnableBackground: true
  minifyStyles: true
  convertColors: true
  convertPathData: true
  convertTransform: true
  removeUnknownsAndDefaults: true
  removeNonInheritableGroupAttrs: true
  removeUselessStrokeAndFill: true
  removeUnusedNS: true
  cleanupIDs: true
  cleanupNumericValues: true
  moveElemsAttrsToGroup: true
  moveGroupAttrsToElems: true
  collapseGroups: true
  mergePaths: true
  convertShapeToPath: true
  convertEllipseToCircle: true
  sortDefsChildren: true
