fragment CaptionedImageSliceType on Case_studyBodyCaptionedimageslicetype {
  type
  primary {
    captioned_image_slice_type_caption
    captioned_image_slice_type_image
    captioned_image_slice_type_image_blurhash
  }
}
