fragment CarouselPhonesSliceType on Case_studyBodyCarouselphonesslicetype {
  type
  fields {
    carousel_phones_slice_type_device_type
    carousel_phones_slice_type_image
    carousel_phones_slice_type_caption
  }
}
