---
name: Build

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build-website:
    name: website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"

      - name: yarn
        run: |
          yarn --frozen-lockfile

      - name: build
        run: |
          yarn build

  build-design-system:
    name: design-system
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"

      - name: yarn
        run: |
          yarn --frozen-lockfile

      - name: storybook
        run: |
          yarn storybook:build
