name: e2e

on:
  workflow_call:
    inputs:
      base-url:
        type: string
        default: https://www.bashkim.com
        description: The base URL to test
        required: false
    secrets:
      VERCEL_AUTOMATION_BYPASS_SECRET:
        description: Secret for accessing vercel environments
        required: false

jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: git checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: node install
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: npm ci
        run: npm ci

      - name: playwright install
        run: npx playwright install --with-deps

      - name: test:e2e
        run: npm run test:e2e
        env:
          PLAYWRIGHT_BASE_URL: ${{ inputs.base-url }}
          PLAYWRIGHT_HEADLESS: true
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: upload report
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: e2e
          path: packages/website-e2e/test-results
          retention-days: 7
