name: lighthouse

on:
  workflow_call:
    inputs:
      base-url:
        type: string
        default: https://www.bashkim.com
        description: The base URL to test via lighthouse ci
        required: false
    secrets:
      VERCEL_AUTOMATION_BYPASS_SECRET:
        description: Secret for accessing vercel environments
        required: false

jobs:
  lighthouse:
    name: ${{ matrix.preset }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        preset:
          - desktop
          # - mobile
    steps:
      - name: git checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: node install
        uses: actions/setup-node@v6
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: lhci install
        run: npm install -g @lhci/cli

      - name: lhci autorun
        run: >
          lhci autorun \
            --collect.settings.preset="${{ matrix.preset }}" \
            --collect.url="${LHCI_COLLECT_URL}"
        env:
          LHCI_COLLECT_URL: ${{ inputs.base-url }}
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: upload results
        uses: actions/upload-artifact@v7
        with:
          name: lhci
          path: ./lhci-results
