name: lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: "18.12.0"
          cache: "yarn"

      - name: yarn
        run: |
          yarn --frozen-lockfile

      - name: prettier
        run: |
          yarn prettier --check .

      - name: eslint
        run: |
          mkdir -p test-results/eslint/
          yarn lint:scripts

      - name: stylelint
        run: |
          mkdir -p test-results/stylelint/
          yarn lint:styles

      - name: vectors
        run: |
          yarn lint:vectors
          git diff --exit-code "*.svg"
