---
name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint:
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'dependabot[bot]' }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: "18.15.0"
          cache: "yarn"

      - name: yarn
        run: |
          yarn --frozen-lockfile

      - name: prettier
        run: |
          yarn prettier --check .

      - name: eslint
        run: |
          mkdir -p test-results/eslint/
          yarn lint:scripts

      - name: stylelint
        run: |
          mkdir -p test-results/stylelint/
          yarn lint:styles

      - name: vectors
        run: |
          yarn lint:vectors
          git diff --exit-code "*.svg"
