name: lighthouse

on:
  deployment_status:

jobs:
  lighthouse:
    if: >
      github.event.deployment_status.state == 'success' &&
      contains(github.event.deployment.environment, 'bashkim-com-website')
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "22.15.0"

      - name: "lhci: install"
        run: npm install -g @lhci/cli

      # - name: "lhci: autorun mobile"
      #   run: >
      #     lhci autorun
      #       --collect.url="${{ github.event.deployment_status.environment_url }}"
      #   env:
      #     VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: "lhci: autorun desktop"
        run: >
          lhci autorun \
            --collect.settings.preset="desktop" \
            --collect.url="${{ github.event.deployment_status.environment_url }}"
        env:
          VERCEL_AUTOMATION_BYPASS_SECRET: ${{ secrets.VERCEL_AUTOMATION_BYPASS_SECRET }}

      - name: "lhci: store"
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-report
          path: ./lhci-results
